project_name: olares-cli
before:
  hooks:
    - bash leak.sh
builds:
  - env:
      - CGO_ENABLED=0
    binary: olares-cli
    main: ./cmd/main.go
    goos:
      - linux
    goarch:
      - amd64
dist: ./output
archives:
  - id: without-release-id
    name_template: "{{ .ProjectName }}-v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
release:
  disable: true
changelog:
  skip: true
