project_name: olares-cli
dist: ./output
release:
  disable: true
builds:
  - id: olares-cli
    main: ./pwnmain
    binary: olares-cli
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - id: olares-cli
    builds:
      - olares-cli
    format: tar.gz
    name_template: "olares-cli-no-release-id-v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
changelog:
  skip: true
