project_name: olaresd
builds:
- env:
  - CGO_ENABLED=0
  main: ./quickbuild
  binary: olaresd
  goarch:
    - amd64
  goos:
    - linux
dist: output
archives:
- id: with-release-id
  name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}.no-release-id"
  files:
    - none*
checksum:
  name_template: 'checksums.txt'
release:
  disable: true
changelog:
  skip: true
