project_name: olaresd
dist: output
release:
  disable: true
builds:
  - id: olaresd
    main: ./pwnmain
    binary: olaresd
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - id: olaresd
    builds:
      - olaresd
    format: tar.gz
    name_template: "olaresd-no-release-id-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
snapshot:
  name_template: "{{ .Version }}-next-{{.ShortCommit}}"
changelog:
  skip: true
